In [1]:
%load_ext autoreload
%autoreload 2

# Juegue un poco para ganar intuición

https://cardgames.io/reversi/

Aca le proponemos una pagina donde puede jugar para ganar intuición en el juego

Note que:
- En el tablero de 8x8 no resulta trivial una estrategia para ganar.
- Luego de jugar un rato podrá notar que ganar las esquinas y/o los bordes puede ser una buena estrategia

# Importar entorno y familiarizarse

In [145]:
from boardgame2 import ReversiEnv
import numpy as np

### Instanciación y reset

In [146]:
board_shape = 8
env = ReversiEnv(board_shape=board_shape)
(board, player) = env.reset()
print(board)
print(player)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
1


### Jugadas válidas

In [147]:
env.get_valid((board, player))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

### Pasos

In [148]:
(board, player), reward, done, _ = env.step([2,4])
print(board, player, done)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]] -1 False


# Implementar una partida completa

Muestreando el esapcio de acción con env.action_space.sample

Notar que el estado es (board, player)

In [149]:
done = False
(board, player) = env.reset()
while not done:
    action = env.action_space.sample()
    print(board)
    print(f'acion: {action}')
    
    print(f'player: {player}')
    (board, player), reward, done, _ = env.step(action)
    

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: (array([1, 3], dtype=int8),)
player: 1


# Implementar sample_valid_actions que muestrea uniformemente las acciones válidas

In [150]:
def sample_valid_actions(state):
    # np.argwhere junto con env.get_valid y randint solucionan el problema en pocas lineas pero puede usar otra estrategia
    valid_actions = np.argwhere(env.get_valid(state) == 1)
    return valid_actions[np.random.randint(len(valid_actions))]

In [151]:
player

1

In [152]:
sample_valid_actions((board, player))

array([3, 5])

In [153]:
done = False
(board, player) = env.reset()
while not done:
    action = sample_valid_actions((board, player))
    print(board)
    print(f'acion: {action}')
    
    print(f'player: {player}')
    (board, player), reward, done, _ = env.step(action)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [3 5]
player: 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [4 5]
player: -1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0 -1 -1 -1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [5 5]
player: 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0 -1  1  1  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [4 6]
player: -1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0 